language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - nightly
install:
  - composer -q install --prefer-dist
  - cp .env.example .env
  - php artisan key:generate
  - cat .env
  - ./vendor/bin/phpunit --coverage-text --configuration phpunit.xml
